### ISSUE TITLE
Bower package?

### ISSUE THREAD

**Issue by StudioLE** [jakwings/toml-j0.4#1]
Any chance of releasing a [bower package](http://bower.io/docs/creating-packages)? There don't appear to be any other toml parsers on there.

**Comment by jakwings** [comment]
I've just created a branch for bower, could you check if it is set up properly? I don't use bower myself. ;-) If everything is ok, I'd register my package.

**Comment by StudioLE** [comment]
I'm relatively new to bower myself too. 

I'm unsure about the `**/.*` line within the ignore array, in my mind that should ignore every file?

However, the below installs successfully:
```
bower install https://github.com/jakwings/toml-j0.4/archive/bower.tar.gz
```

**Comment by jakwings** [comment]
Ok, looks good. Now you can install it via `bower install toml-j0.4`. Further questions are welcome!

`**/.*` matches all dot-files in all directories (including sub-directories). Dot-files are `.gitignore, .npmignore` and the like, excluding bower.json.
