### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by iarna** [jakwings/toml-j0.4#3]
I just wanted to say thank you for writing this (and saving me from having to. =D)

This is between 20x and 200x faster than [toml](https://www.npmjs.com/package/toml), which is the only other TOML parser that's actually complete. The others either don't implement v0.4 or fail even the most basic of tests (loading the examples from the spec).

I put together a [survey of TOML parsers](https://github.com/iarna/toml-parser-survey#readme):

Performance with the spec examples:
![perf: toml at 17 ops/sec, toml-j0.4 at 241 ops/sec, others failing assertions](https://pbs.twimg.com/media/DBJEipKU0AE7FAx.jpg)

Performance with a much "larger" file (150k):
![perf: toml at 0.08 ops/sec, toml-j0.4 at 18 ops/sec](https://pbs.twimg.com/media/DBJNp91V0AQh_Mo.jpg)

**Comment by iology** [comment]
Glad it helps. ;-)

**Comment by erquhart** [comment]
@iology this is awesome validation from an npm team member! Maybe even consider placing that first image in your readme up top? Great work on this lib!
